version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ganache-cli
    versions:
    - "> 6.12.1, < 6.13"
  - dependency-name: "@gnosis.pm/owl-token"
    versions:
    - ">= 3.2.a, < 3.3"
  - dependency-name: "@openzeppelin/contracts"
    versions:
    - ">= 3.a, < 4"
  - dependency-name: prettier-plugin-solidity
    versions:
    - 1.0.0-beta.10
    - 1.0.0-beta.3
    - 1.0.0-beta.4
    - 1.0.0-beta.5
    - 1.0.0-beta.6
    - 1.0.0-beta.7
    - 1.0.0-beta.8
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: web3-core
    versions:
    - 1.3.4
    - 1.3.5
  - dependency-name: web3-utils
    versions:
    - 1.3.4
  rebase-strategy: disabled
