/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="@openeth/truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "BatchExchange"): TruffleContracts.BatchExchangeContract;
      require(
        name: "BatchExchangeViewer"
      ): TruffleContracts.BatchExchangeViewerContract;
      require(name: "Context"): TruffleContracts.ContextContract;
      require(
        name: "DeployableERC20Detailed"
      ): TruffleContracts.DeployableERC20DetailedContract;
      require(
        name: "EpochTokenLocker"
      ): TruffleContracts.EpochTokenLockerContract;
      require(
        name: "EpochTokenLockerTestInterface"
      ): TruffleContracts.EpochTokenLockerTestInterfaceContract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ERC20Detailed"): TruffleContracts.ERC20DetailedContract;
      require(name: "ERC20Mintable"): TruffleContracts.ERC20MintableContract;
      require(name: "GnosisMath"): TruffleContracts.GnosisMathContract;
      require(
        name: "GnosisStandardToken"
      ): TruffleContracts.GnosisStandardTokenContract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "MinterRole"): TruffleContracts.MinterRoleContract;
      require(name: "MockContract"): TruffleContracts.MockContractContract;
      require(name: "MockInterface"): TruffleContracts.MockInterfaceContract;
      require(name: "MultiCaller"): TruffleContracts.MultiCallerContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(name: "Proxied"): TruffleContracts.ProxiedContract;
      require(name: "Proxy"): TruffleContracts.ProxyContract;
      require(name: "SnappAuction"): TruffleContracts.SnappAuctionContract;
      require(name: "SnappBase"): TruffleContracts.SnappBaseContract;
      require(name: "SnappBaseCore"): TruffleContracts.SnappBaseCoreContract;
      require(name: "Token"): TruffleContracts.TokenContract;
      require(
        name: "TokenConservationWrapper"
      ): TruffleContracts.TokenConservationWrapperContract;
      require(name: "TokenOWL"): TruffleContracts.TokenOWLContract;
      require(name: "TokenOWLProxy"): TruffleContracts.TokenOWLProxyContract;
    }
  }
}
